// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://hulgfvssgnpcnxafnsba.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh1bGdmdnNzZ25wY254YWZuc2JhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzMzMjQyNTAsImV4cCI6MjA0ODkwMDI1MH0.ylDGq3CZoWzyXWQhkswLxnXoeW4d_xLdvnQaBKMMsZo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);